name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main_en.tex
          latexmk_shell_escape: true
          os: debian

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main_en.pdf

      - name: Upload to orphan branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create orphan branch for PDFs (no history)
          git checkout --orphan pdf-output
          git rm -rf .

          # Add only the PDF
          cp ../main_en.pdf ./manuscript.pdf
          git add manuscript.pdf
          git commit -m "Update PDF from commit ${{ github.sha }}"
          git push -f origin pdf-output
