name: Build LaTeX document
on: [push]

permissions:
  contents: write # This allows pushing to the repo

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main_en.tex
          latexmk_shell_escape: true
          os: debian

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main_en.pdf

      - name: Upload to orphan branch
        run: |
          # Store PDF path
          PDF_PATH="${PWD}/main_en.pdf"


          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create orphan branch for PDFs (no history)
          git checkout --orphan pdf-output

          # Add only the PDF
          cp "${PDF_PATH}" ./manuscript.pdf
          git add manuscript.pdf
          git commit -m "Update PDF from ${{ github.event.head_commit.timestamp }}"
          git push -f origin pdf-output
